#!/bin/bash

# Sample: 
# aws ec2 describe-security-groups --output table --profile staging5-super-user --filters "Name=tag:Name, Values=elasticsearch" --query "SecurityGroups[*].{name:Tags[?Key=='Name']|[0].Value,groupname:GroupName,groupid:GroupId,vpcid:VpcId}"
source "`dirname $0`"/../aws-profiles
while getopts ":ha:n:" opt; do
  case ${opt} in
    h )
      echo "Options:"
      echo "    -h  Display this help message."
      echo "    -a  AWS Account or set env var AWS_ACCOUNT."
      echo "    -n  Name of the security group or partial name."
      exit 0
      ;;
    a )
      ACCOUNT=$OPTARG
      ;;
    n )
      NAME=$OPTARG
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      ;;
  esac
done
shift $((OPTIND -1))

if [[ -z "$ACCOUNT" ]]; then
  if [[ -z "$AWS_PROFILE" ]] ; then
    echo "Either set env var AWS_ACCOUNT or provide it via -a option."
    exit 1
  else
    ACCOUNT=$AWS_ACCOUNT
  fi
fi

PROFILE=${!ACCOUNT}
echo
echo "ACCOUNT :: $ACCOUNT"
QUERY="SecurityGroups[*].{name:Tags[?Key=='Name']|[0].Value,groupname:GroupName,groupid:GroupId,vpcid:VpcId}"
OUTPUT="table"

if [ -z "$NAME" ]; then
  aws ec2 describe-security-groups \
  --query $QUERY \
  --output $OUTPUT \
  --profile=$PROFILE
else
  aws ec2 describe-security-groups \
  --query $QUERY \
  --output $OUTPUT \
  --profile=$PROFILE \
  --filters "Name=tag:Name, Values=*$NAME*"
fi
echo
